//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosPortal
    {
        public string IdFolioDeServicio { get; set; }
        public string Prioridad { get; set; }
        public string TipoServicio { get; set; }
        public string SucursalConsignatario { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<System.DateTime> FechaRealizarServicio { get; set; }
        public string OrdenServicio { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Divisa { get; set; }
        public string Te { get; set; }
        public Nullable<System.DateTime> HoraEnvio { get; set; }
        public Nullable<System.DateTime> Actualización { get; set; }
        public string Estatus { get; set; }
    }
}
